image: node:14

pipelines:
  branches:
    feature/*:
      - step:
          name: Sync Repositories
          script:
            - git clone https://github.com/$GITHUB_USERNAME/spring-boot-portfolio.git
            - cd spring-boot-portfolio
            - git config user.name $GITHUB_USERNAME
            - git config user.email $USER_EMAIL
            - git remote set-url origin https://github.com/$GITHUB_USERNAME/spring-boot-portfolio.git
            - git pull https://${USERNAME}:${BITBUCKET_APP_PASSWORD}@bitbucket.org/${USERNAME}/spring-boot-portfolio.git
            - git push origin HEAD:$BITBUCKET_BRANCH
  default:
    - step:
        name: Sync Repositories
        script:
          - git clone https://github.com/$GITHUB_USERNAME/spring-boot-portfolio.git
          - cd spring-boot-portfolio
          - git config user.name $GITHUB_USERNAME
          - git config user.email $USER_EMAIL
          - git remote set-url origin https://${USERNAME}@bitbucket.org/${USERNAME}/spring-boot-portfolio.git
          - git pull
          - git push origin HEAD:$BITBUCKET_BRANCH
definitions:
  caches:
    node: /usr/local/bin/npm
